version: 0.2

phases:
  install:
    commands:
      - jq --version
      - echo $CODEBUILD_SOURCE_VERSION 
      - echo installing serverless
      - npm install -g serverless
  pre_build:
    commands:
      - echo installing NPM dependecies...
      - npm install
      - cd ${SERVICE_PATH} && npm install && cd -
  build:
    commands:
      - echo deployment started `date`....
      - |
        if [ "${SERVICE_PATH}" = "Service/Default" ]; then
          cd ${SERVICE_PATH} && serverless deploy -s $ENV_NAME && cd -;
          sleep 5;
          cd ${SERVICE_PATH_1} && serverless deploy -s $ENV_NAME && cd -;
        fi
        cd ${SERVICE_PATH} && serverless deploy -s $ENV_NAME && cd -;
  post_build:
    commands:
      - echo serverless deployment completed successfully.
cache:
  paths:
    - node_modules
    - ${SERVICE_PATH}/node_modules