version: 0.2

phases:
  install:
    commands:
      - jq --version
      - echo $CODEBUILD_SOURCE_VERSION 
      - echo installing serverless
      - npm install -g serverless
  pre_build:
    commands:
      - echo installing NPM dependecies...
      - npm install
      - cd ${SERVICE_PATH} && npm install && cd -
  build:
    commands:
      - echo deployment started `date`....
      - cd ${SERVICE_PATH} && serverless deploy -s $ENV_NAME && cd -;
      - api_gw_url=`aws cloudformation describe-stacks \--stack-name Develope2-dev \--query "Stacks[0].Outputs[*].{OutputKey:OutputKey,OutputValue:OutputValue}" | jq '.[] | select(.OutputKey=="HelloLambdaFunctionQualifiedArn") | .OutputValue'`
  post_build:
    commands:
      - echo $api_gw_url
      - echo serverless deployment completed successfully.
cache:
  paths:
    - node_modules
    - ${SERVICE_PATH}/node_modules