version: 0.2

phases:
  install:
    commands:
      - echo installing serverless
      - npm install -g serverless
  pre_build:
    commands:
      - echo installing NPM dependecies...
      - npm install
  build:
    commands:
      - echo deployment started `date`....
      - sls deploy --package /Default
  post_build:
    commands:
      - echo serverless deployment completed successfully.