service: default
#app and org for use with dashboard.serverless.com
#app: cicd_1-0
org: wsorgsls


#environment:
#    ENV_NAME:  ${param:ENV_NAME}



provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev
  region: us-east-1



functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
